CREATE TYPE sense AS ENUM (
    'See',
    'Touch',
    'Taste',
    'Smell',
    'Hear'
);

CREATE TABLE trips (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    trip_name TEXT NOT NULL,
    description TEXT NOT NULL,
    element_one TEXT NOT NULL,
    sense_one sense,
    element_two TEXT NOT NULL,
    sense_two sense NOT NULL,
    element_three TEXT NOT NULL,
    sense_three sense NOT NULL,
    element_four TEXT NOT NULL,
    sense_four sense NOT NULL,
    element_five TEXT NOT NULL,
    sense_five sense NOT NULL
);