INSERT INTO trips (trip_name, description, element_one, sense_one, resource_one, element_two, sense_two, resource_two, element_three, sense_three, resource_three, element_four, sense_four, resource_four, element_five, sense_five, resource_five)
VALUES 
    ('France', 
    'Oui, oui! It is true - you are going to France! You will be the magic and romance of this beloved country from home today. Bon Voyage!', 
    'To make the most of your French experience, you will spend the first day prepping the delicious pastry most commonly associated with France, the croissant.  Complete steps 1 - 7 leaving the dough in the refrigerator over night so that it will be ready to finish and bake when you wake!', 
    'Taste', 
    'https://www.saveur.com/best-croissants-recipe/',
    'Learn about the 5 Types of French Coffee so you can order like a regular. Enjoy the delicious aromas as your brew yourself un café and bake the croissants.', 
    'Smell', 
    'https://luxeadventuretraveler.com/5-types-french-coffees-explained/',
    'There are endless sights to see in France but a class is of course the Louvre in Paris.  Take a virtual tour of a few of the most popular exhibits.  It is not every day you get to sip espresso and eat a flaky pastry in a museum!', 
    'See', 
    'https://www.louvre.fr/en/visites-en-ligne',
    'Pump up the tunes when you finish your tour with this French Pop Playlist', 
    'Hear', 
    'https://open.spotify.com/playlist/0r4vVaS4v86NxUxONAQysN?si=UjPZ34LfQn-kIi0l6AY8pg',
    'A few other ways you can maximine the feel of your trip to France including wearing a silky scarf, setting up a "bisto" with two sturdy but delicate chairs in the sunshine, and tearing apart a crust baguette.', 
    'Touch',
    'https://www.article.com/pla/3807/noir-dining-chair?forceCurrencyId=1&artcl_campignID=852956878&artcl_network=g&artcl_adgroupid=44057342780&artcl_keyword=&artcl_source=google&gclid=Cj0KCQjwzN71BRCOARIsAF8pjfiPjS39YM_OvrgK1kkmKhmQmZFcfPyjHh4kRP5G4zxyx4BPsZW-XT4aAnXXEALw_wcB'
    ),
    ('Underwater', 
    'Look out - shark!  Made you look.  Today, we are heading under the sea.  This will be a relaxing and relatively low-effort trip if you would like it to be', 
    'You will definitely want to order this amazing, handmade Ocean Salt scrub from Lush for your Underwater experience.', 
    'Touch', 
    'https://www.lushusa.com/face/cleansers-scrubs/ocean-salt/9999902128.html',
    'Warm your insides with the taste of the sea using a 15-Minute Miso Soup recipe', 
    'Taste', 
    'https://minimalistbaker.com/15-minute-miso-soup-with-greens-and-tofu/',
    'The description of the Saltaire candle reads: "The healing powers of salty air has been known since the beginning of time and we wanted to capture that smell." ', 
    'Smell', 
    'https://www.mersea.com/products/saltaire-canister-candle?_pos=3&_sid=68cd2508b&_ss=r',
    'Enjoy the soothing sounds of the ocean all day long with the Sounds of the Sea', 
    'Hear', 
    'https://open.spotify.com/album/6xJdOQAfxw89LXryfhWHED',
    'Take in the sights of the largest coral reef system in the world, the wondrous Great Barrier Reef.', 
    'See',
    'https://watch.smithsonianchannel.com/details/series/david-attenboroughs-great-barrier-reef/?utm_medium=paid&utm_source=search&utm_campaign=CF&utm_content=CF_copy&gclid=Cj0KCQjwzN71BRCOARIsAF8pjfielhhC5Q9UXvV6LFikRL7f5bRuJDusibQqQuByFsCIVtj-wPfHUFQaAluOEALw_wcB'
    );